<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="px4_quadcopter">
  
  <!-- Parameters -->
  <xacro:property name="body_radius" value="0.15"/>
  <xacro:property name="body_height" value="0.08"/>
  <xacro:property name="arm_length" value="0.25"/>
  <xacro:property name="arm_width" value="0.03"/>
  <xacro:property name="prop_radius" value="0.12"/>
  <xacro:property name="prop_height" value="0.02"/>
  
  <!-- Materials -->
  <material name="light_grey">
    <color rgba="0.8 0.8 0.8 1.0"/>
  </material>
  
  <material name="dark_grey_transparent">
    <color rgba="0.4 0.4 0.4 0.6"/>
  </material>

  <!-- Base link (main body and arms) -->
  <link name="base_link">
    <visual>
      <!-- Main body -->
      <geometry>
        <box size="0.20 0.10 ${body_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="light_grey"/>
    </visual>
    
    <visual>
      <!-- Front-Right arm -->
      <geometry>
        <cylinder radius="${arm_width/2}" length="${arm_length}"/>
      </geometry>
      <origin xyz="${arm_length/2*0.707} -${arm_length/2*0.707} 0" rpy="0 1.5708 -0.785398"/>
      <material name="light_grey"/>
    </visual>
    
    <visual>
      <!-- Front-Right motor mount -->
      <geometry>
        <cylinder radius="${arm_width/1.5}" length="${arm_width*1.5}"/>
      </geometry>
      <origin xyz="${arm_length*0.707} -${arm_length*0.707} ${arm_width*0.75}" rpy="0 0 0"/>
      <material name="light_grey"/>
    </visual>
    
    <visual>
      <!-- Back-Right arm -->
      <geometry>
        <cylinder radius="${arm_width/2}" length="${arm_length}"/>
      </geometry>
      <origin xyz="-${arm_length/2*0.707} -${arm_length/2*0.707} 0" rpy="0 1.5708 0.785398"/>
      <material name="light_grey"/>
    </visual>
    
    <visual>
      <!-- Back-Right motor mount -->
      <geometry>
        <cylinder radius="${arm_width/1.5}" length="${arm_width*1.5}"/>
      </geometry>
      <origin xyz="-${arm_length*0.707} -${arm_length*0.707} ${arm_width*0.75}" rpy="0 0 0"/>
      <material name="light_grey"/>
    </visual>
    
    <visual>
      <!-- Back-Left arm -->
      <geometry>
        <cylinder radius="${arm_width/2}" length="${arm_length}"/>
      </geometry>
      <origin xyz="-${arm_length/2*0.707} ${arm_length/2*0.707} 0" rpy="0 1.5708 -0.785398"/>
      <material name="light_grey"/>
    </visual>
    
    <visual>
      <!-- Back-Left motor mount -->
      <geometry>
        <cylinder radius="${arm_width/1.5}" length="${arm_width*1.5}"/>
      </geometry>
      <origin xyz="-${arm_length*0.707} ${arm_length*0.707} ${arm_width*0.75}" rpy="0 0 0"/>
      <material name="light_grey"/>
    </visual>
    
    <visual>
      <!-- Front-Left arm -->
      <geometry>
        <cylinder radius="${arm_width/2}" length="${arm_length}"/>
      </geometry>
      <origin xyz="${arm_length/2*0.707} ${arm_length/2*0.707} 0" rpy="0 1.5708 0.785398"/>
      <material name="light_grey"/>
    </visual>
    
    <visual>
      <!-- Front-Left motor mount -->
      <geometry>
        <cylinder radius="${arm_width/1.5}" length="${arm_width*1.5}"/>
      </geometry>
      <origin xyz="${arm_length*0.707} ${arm_length*0.707} ${arm_width*0.75}" rpy="0 0 0"/>
      <material name="light_grey"/>
    </visual>

    <!-- Collision (single rectangular body) -->
    <collision>
      <geometry>
        <box size="0.20 0.10 ${body_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <!-- Inertial properties -->
    <inertial>
      <mass value="1.5"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0347563" ixy="0.0" ixz="0.0"
               iyy="0.0347563" iyz="0.0"
               izz="0.0168750"/>
    </inertial>
  </link>
  
  <!-- Propellers -->
  <link name="front_right_propeller">
    <visual>
      <geometry>
        <cylinder radius="${prop_radius}" length="${prop_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="dark_grey_transparent"/>
    </visual>
  </link>
  
  <link name="front_left_propeller">
    <visual>
      <geometry>
        <cylinder radius="${prop_radius}" length="${prop_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="dark_grey_transparent"/>
    </visual>
  </link>
  
  <link name="back_right_propeller">
    <visual>
      <geometry>
        <cylinder radius="${prop_radius}" length="${prop_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="dark_grey_transparent"/>
    </visual>
  </link>
  
  <link name="back_left_propeller">
    <visual>
      <geometry>
        <cylinder radius="${prop_radius}" length="${prop_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="dark_grey_transparent"/>
    </visual>
  </link>
  
  <!-- Joints to position propellers -->
  <joint name="front_right_prop_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_right_propeller"/>
    <origin xyz="${arm_length*0.707} -${arm_length*0.707} ${prop_height/2 + arm_width/2}" rpy="0 0 0"/>
  </joint>
  
  <joint name="front_left_prop_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_left_propeller"/>
    <origin xyz="${arm_length*0.707} ${arm_length*0.707} ${prop_height/2 + arm_width/2}" rpy="0 0 0"/>
  </joint>
  
  <joint name="back_right_prop_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_right_propeller"/>
    <origin xyz="-${arm_length*0.707} -${arm_length*0.707} ${prop_height/2 + arm_width/2}" rpy="0 0 0"/>
  </joint>
  
  <joint name="back_left_prop_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_left_propeller"/>
    <origin xyz="-${arm_length*0.707} ${arm_length*0.707} ${prop_height/2 + arm_width/2}" rpy="0 0 0"/>
  </joint>
  
  <!-- IMU link -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
