# PX4 Messages Bridge Configuration
# This file configures the unified bridge manager and all its converters

px4_bridge_manager:
  ros__parameters:
    # === Global Configuration ===
    # Vehicle namespace for ROS topics
    vehicle_namespace: "vehicle"
     
    # === PX4 → ROS Converter Configuration ===
    px4_to_ros:
      # Publishing options
      publish_pose: true        # shown as /{vehicle_namespace}/pose
      publish_path: true        # shown as /{vehicle_namespace}/path
      publish_odometry: false   # shown as /{vehicle_namespace}/odom
      publish_imu: true     # shown as /{vehicle_namespace}/imu
      
      # Path tracking configuration
      path_config:
        max_path_size: 100       # Path size limit (0=disabled, inf=unlimited, >0=limited). 
      
      # Frame configuration
      output_frame_id: "odom"    # Frame ID for all output messages
      child_frame_id: "base_link" # Child frame for odometry
      
      # TF Publishing Configuration
      tf_publishing:
        enable_tf: true                    # Master TF enable/disable
        publish_odom_tf: true              # Always publish odom -> base_link (quadrotor always visible)
        publish_map_tf: false              # Disable map frame by default (enable when mocap/GPS available)
        
        # Frame names
        map_frame: "map"
        odom_frame: "odom" 
        base_link_frame: "base_link"
        
        # Publishing rates (Hz)
        tf_rate: 100.0                     
        map_tf_rate: 100.0                 
    
    # === ROS → PX4 Converter Configuration ===
    ros_to_px4:
      # External odometry input (e.g., from camera/LIDAR SLAM or Mocap)
      # For know we just assume the external odom facing the same direction as the px4/fmu
      # To Do: additional matrix conversion parameters for any other case
      external_odometry:
        enable: false   # Set to true when you have external VIO/SLAM system
        input_topic: "/odom/sample"  # Common: /Odometry, /camera/odom/sample, /rtabmap/odom
        quality_threshold: 0.5       # Minimum odometry quality to accept
    
    # Visualization Configuration
    visualizer:
      enable: false                      # Launch RViz2 for bridge visualization (true/false)
      config_file: ""                    # Path to custom RViz config file (empty = use default)
      robot_model:
        enable: false                    # Enable robot model in RViz (true/false)
        model_file: ""                   # Path to custom URDF/xacro file (empty = use default quadcopter)
   